CXX= g++
CXXFLAGS = -std=c++0x
LDFLAGS = -lboost_date_time

OBJS = f.o g.o main
SRCS = f.cpp g.cpp main.cpp
HEADERS = f.h g.h

#target: dependencies
		 #rule to build

#lecture1: lecture1.cpp functions.hpp functions.cpp
#		${CXX} ${CXXFLAGS} lecture1.cpp functions.cpp -o lecture1

main: ${SRCS} ${HEADERS}
		${CXX} ${CXXFLAGS} ${SRCS} -o main
		



